apiVersion: v1
kind: Service
metadata:
  name: my-stateful-app-service
  labels:
    app: my-stateful-app
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # This makes it a headless service
  selector:
    app: my-stateful-app # Must match the StatefulSet's Pods